# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-08 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogo', '0003_auto_20190408_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_id',
        ),
    ]
